on: [push]

jobs:
  ActionJob:
    runs-on: ubuntu-latest
    name: CI for the action
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Run pharo Tests
        id: tests
        uses: akevalion/CoveragePic@v1
        with:
          # removes-repo: ''
          baseline: 'CoveragePic'
          pharo: 'Pharo11'
          group: 'default'
          tests: 'Morphic-Test*'
      - name: save artefacts
        uses: actions/upload-artifact@v2
        with:
          name: 'to-download'
          path: '/tmp/coverage.png'
      - name: Generate list using Markdown
        run: |
          echo "This is the lead in sentence for the list" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY # this is a blank line
          echo "- Lets add a bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- Lets add a second bullet point" >> $GITHUB_STEP_SUMMARY
          echo "- How about a third one?" >> $GITHUB_STEP_SUMMARY
